group = com.github.junkydeveloper.jetbrainsflintplugin
version = 0.0.1

# RustRover build base (exact build: RR-261.23567.140182 = 2026.1)
platformVersion = 2026.1

pluginRepositoryUrl = https://github.com/JunkyDeveloper/jetbrains-flint-plugin

# Opt-out flag for bundling Kotlin standard library -> https://jb.gg/intellij-platform-kotlin-stdlib
kotlin.stdlib.default.dependency = false

# Enable Gradle Configuration Cache -> https://docs.gradle.org/current/userguide/configuration_cache.html
org.gradle.configuration-cache = true

# Enable Gradle Build Cache -> https://docs.gradle.org/current/userguide/build_cache.html
org.gradle.caching = true
