package com.github.junkydeveloper.jetbrainsflintplugin.services

import java.nio.file.Files
import java.nio.file.Path

/** Run aborts: an unmarked `.cargo/config.toml` would be clobbered. */
class CargoConfigConflict(message: String) : RuntimeException(message)

/**
 * Writes `<clone>/.cargo/config.toml` redirecting flint-steel's `steel-*` /
 * optional `flint-core` git deps to local paths. Only touches the file when it
 * is absent or owned by us (marker header); otherwise aborts the run so a
 * hand-written config is never destroyed.
 */
object CargoConfigWriter {

    const val MARKER = "# GENERATED BY flint plugin — do not edit"

    private const val STEEL_GIT = "https://github.com/Steel-Foundation/SteelMC.git"
    private const val FLINT_CORE_GIT = "https://github.com/FlintTestMC/flint-core.git"

    /**
     * @param steelCrates name -> absolute crate dir (from SteelWorkspaceResolver)
     * @param localFlintCorePath optional local flint-core override (blank = skip)
     */
    fun write(cloneDir: Path, steelCrates: Map<String, Path>, localFlintCorePath: String) {
        val cargoDir = cloneDir.resolve(".cargo")
        val configFile = cargoDir.resolve("config.toml")

        if (Files.exists(configFile)) {
            val firstLine = Files.newBufferedReader(configFile).use { r ->
                generateSequence { r.readLine() }.firstOrNull { it.isNotBlank() }
            }
            if (firstLine?.trim() != MARKER) {
                throw CargoConfigConflict(
                    "$configFile exists and is not flint-managed.\n" +
                        "Remove or back it up, then re-run (expected header: \"$MARKER\").",
                )
            }
        }

        val sb = StringBuilder()
        sb.appendLine(MARKER).appendLine()
        sb.appendLine("[patch.\"$STEEL_GIT\"]")
        for ((name, dir) in steelCrates) {
            sb.appendLine("$name = { path = ${toml(dir.toAbsolutePath().toString())} }")
        }
        if (localFlintCorePath.isNotBlank()) {
            sb.appendLine()
            sb.appendLine("[patch.\"$FLINT_CORE_GIT\"]")
            sb.appendLine("flint-core = { path = ${toml(localFlintCorePath)} }")
        }

        Files.createDirectories(cargoDir)
        Files.writeString(configFile, sb.toString())
    }

    private fun toml(value: String): String =
        "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\""
}
